export interface RadOdontograma {
  regiao: string
  idBotao18: string
  isBotao18: boolean
  idBotao17: string
  isBotao17: boolean
  idBotao16: string
  isBotao16: boolean
  idBotao15: string
  isBotao15: boolean
  idBotao14: string
  isBotao14: boolean
  idBotao13: string
  isBotao13: boolean
  idBotao12: string
  isBotao12: boolean
  idBotao11: string
  isBotao11: boolean
  idBotao21: string
  isBotao21: boolean
  idBotao22: string
  isBotao22: boolean
  idBotao23: string
  isBotao23: boolean
  idBotao24: string
  isBotao24: boolean
  idBotao25: string
  isBotao25: boolean
  idBotao26: string
  isBotao26: boolean
  idBotao27: string
  isBotao27: boolean
  idBotao28: string
  isBotao28: boolean
  idBotao55: string
  isBotao55: boolean
  idBotao54: string
  isBotao54: boolean
  idBotao53: string
  isBotao53: boolean
  idBotao52: string
  isBotao52: boolean
  idBotao51: string
  isBotao51: boolean
  idBotao61: string
  isBotao61: boolean
  idBotao62: string
  isBotao62: boolean
  idBotao63: string
  isBotao63: boolean
  idBotao64: string
  isBotao64: boolean
  idBotao65: string
  isBotao65: boolean
  idBotao85: string
  isBotao85: boolean
  idBotao84: string
  isBotao84: boolean
  idBotao83: string
  isBotao83: boolean
  idBotao82: string
  isBotao82: boolean
  idBotao81: string
  isBotao81: boolean
  idBotao71: string
  isBotao71: boolean
  idBotao72: string
  isBotao72: boolean
  idBotao73: string
  isBotao73: boolean
  idBotao74: string
  isBotao74: boolean
  idBotao75: string
  isBotao75: boolean
  idBotao48: string
  isBotao48: boolean
  idBotao47: string
  isBotao47: boolean
  idBotao46: string
  isBotao46: boolean
  idBotao45: string
  isBotao45: boolean
  idBotao44: string
  isBotao44: boolean
  idBotao43: string
  isBotao43: boolean
  idBotao42: string
  isBotao42: boolean
  idBotao41: string
  isBotao41: boolean
  idBotao31: string
  isBotao31: boolean
  idBotao32: string
  isBotao32: boolean
  idBotao33: string
  isBotao33: boolean
  idBotao34: string
  isBotao34: boolean
  idBotao35: string
  isBotao35: boolean
  idBotao36: string
  isBotao36: boolean
  idBotao37: string
  isBotao37: boolean
  idBotao38: string
  isBotao38: boolean
}
