export interface RadiografiaExtraoraisModel {
  idRadiografiaExtraorais: string
  isRadiografiaExtraorais: boolean
  idPanoramica: string
  isPanoramica: boolean
  idPA: string
  isPA: boolean
  idCefalometricaPerfil: string
  isCefalometricaPerfil: boolean
  idMaoPunho: string
  isMaoPunho: boolean
  idTracado: string
  isTracado: boolean
  idTipEdge: string
  isTipEdge: boolean
  idTweed: string
  isTweed: boolean
  idDelmanto: string
  isDelmanto: boolean
  idPetrovic: string
  isPetrovic: boolean
  idErupcao3Molar: string
  isErupcao3Molar: boolean
  idRicketts: string
  isRicketts: boolean
  idBimler: string
  isBimler: boolean
  idJarabak: string
  isJarabak: boolean
  idIBEO: string
  isIBEO: boolean
  idDowns: string
  isDowns: boolean
  idUspUnicamp: string
  isUspUnicamp: boolean
  idRickettsFrontal: string
  isRickettsFrontal: boolean
  idAdenoides: string
  isAdenoides: boolean
  idSchwarz: string
  isSchwarz: boolean
  idPadraoProfis: string
  isPadraoProfis: boolean
  idMacNamara: string
  isMacNamara: boolean
  idSteiner: string
  isSteiner: boolean
  idVJMJ: string
  isVJMJ: boolean
  idUSP: string
  isUSP: boolean
}
