export interface DocumentacoesModel {
  idDocumentacoes: string
  isDocumentacoes: boolean
  idClassificacaoAngle: string
  isClassificacaoAngle: boolean
  idClasseI: string
  isClasseI: boolean
  idClasseII: string
  isClasseII: boolean
  idClasseIII: string
  isClasseIII: boolean
  idPanoramica: string
  isPanoramica: boolean
  idCefalometricaPerfil: string
  isCefalometricaPerfil: boolean
  idTracadoAvulso: string
  isTracadoAvulso: boolean
  idKit8Fotos: string
  isKit8Fotos: boolean
  idEscanIntraOralModImp: string
  isEscanIntraOralModImp: boolean
  idEscanIntraOralSemModImp: string
  isEscanIntraOralSemModImp: boolean
  idModGessoZocado: string
  isModGessoZocado: boolean
  idModGessoTrab: string
  isModGessoTrab: boolean
  idPeriapicalIncisivosBiteWing: string
  isPeriapicalIncisivosBiteWing: boolean
  idPeriapicalCompletoBiteWing: string
  isPeriapicalCompletoBiteWing: boolean
  idSmartAligner: string
  isSmartAligner: boolean
  idInvisalign: string
  isInvisalign: boolean
  idOrthoAligner: string
  isOrthoAligner: boolean
  idKika: string
  isKika: boolean
  idTracado: string
  isTracado: boolean
  idTipEdge: string
  isTipEdge: boolean
  idTweed: string
  isTweed: boolean
  idDelmanto: string
  isDelmanto: boolean
  idPetrovic: string
  isPetrovic: boolean
  idErupcao3Molar: string
  isErupcao3Molar: boolean
  idRicketts: string
  isRicketts: boolean
  idBimler: string
  isBimler: boolean
  idJarabak: string
  isJarabak: boolean
  idIBEO: string
  isIBEO: boolean
  idDowns: string
  isDowns: boolean
  idUspUnicamp: string
  isUspUnicamp: boolean
  idRickettsFrontal: string
  isRickettsFrontal: boolean
  idAdenoides: string
  isAdenoides: boolean
  idSchwarz: string
  isSchwarz: boolean
  idPadraoProfis: string
  isPadraoProfis: boolean
  idMacNamara: string
  isMacNamara: boolean
  idSteiner: string
  isSteiner: boolean
  idVJMJ: string
  isVJMJ: boolean
  idUSP: string
  isUSP: boolean
}
