export interface ProtCirurGuiadaModel {
  idProtCirGuiada: string
  isProtCirGuiada: boolean
  idLaboratorio: string
  idProcedimento: string
  idCompass3d: string
  isCompass3d: boolean
  idMandibula: string
  isMandibula: boolean
  idSmartSolution: string
  isSmartSolution: boolean
  idMaxila: string
  isMaxila: boolean
  idCirurgiaGuiadaParcial: string
  isCirurgiaGuiadaParcial: boolean
  idLaudoImpressaoCGP: string
  isLaudoImpressaoCGP: boolean
  idTomoDicomCGP: string
  isTomoDicomCGP: boolean
  idEscaneamentoIntraoralCGP: string
  isEscaneamentoIntraoralCGP: boolean
  idPlanejamentoCGP: string
  isPlanejamentoCGP: boolean
  idPlanejamentoFuroCGP: string
  isPlanejamentoFuroCGP: boolean
  idCirurgiaGuiadaTotal: string
  isCirurgiaGuiadaTotal: boolean
  idLaudoImpressaoCGT: string
  isLaudoImpressaoCGT: boolean
  idTomoDicomCGT: string
  isTomoDicomCGT: boolean
  idTomoProteseDicomCGT: string
  isTomoProteseDicomCGT: boolean
  idPlanejamentoCGT: string
  isPlanejamentoCGT: boolean
  idPlanejamentoFuroCGT: string
  isPlanejamentoFuroCGT: boolean
}
